### ISSUE TITLE
Cannot update BoxView Document

### ISSUE THREAD

**Issue by hoang1417** [getlua/boxviewrb#10]
I can create, view, delete but update:

![screen shot 2015-02-12 at 18 40 59](https://cloud.githubusercontent.com/assets/4915433/6166845/ce6afec0-b2e6-11e4-937f-443cf24d5b9c.png)

Any ideas about this ideas? Thanks.

**Comment by vinnymac** [comment]
Looks like you got a 405 - Method Not Allowed error. I will try and investigate this when I have time. Have you been able to reproduce it? Are you still having this issue?
