### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by denodster** [getlua/boxviewrb#12]
It's been over a year since the last release, My company is forced to use a privately hosted fork rather than the official Gem, even though our fixes are merged in. Is there anything I can do to speed up a new release?

**Comment by vinnymac** [comment]
I must apologize, I haven't been able to add as many updates to this library as it deserves. Nor have I given it enough attention and been able to add the new beta features. I just published a new version to [rubygems](https://rubygems.org/gems/boxview.rb). I will keep versions up to date on rubygems better in the future. Also thanks for letting me know that I forgot to push this.
