### ISSUE TITLE
Urgent issue need to be solved : How to fetch .png or .jpg format from pdf/ppt/docx

### ISSUE THREAD

**Issue by VanathiTrek** [getlua/boxviewrb#9]
I am uploading pdf/ppt/docx to BOX and while fetching it from the ZIP i normally get converted HTML and SVG assets, but i need .png format instead of svg
I found this in BOX document : 
"GET /documents/{id}/content.{extension}

Fetches a document in the form specified by extension, which can be one of pdf or zip. If an extension is not specified, the document’s original format is returned. The zip file will contain the converted HTML and SVG assets, and optionally the PNG assets if the non_svg parameter was specified on upload. " 

URL: https://developers.box.com/view/

Where it is said non_svg parameter to specify on upload, have anyOne tried this.

**Comment by vinnymac** [comment]
@VanathiTrek BoxView did not originally support this feature. Feel free to create a pull request for this feature if you need it. If enough people ask for it, I may find the time to work on adding it to the [show method](https://github.com/getlua/boxviewrb/blob/master/lib/boxview/document.rb#L104) myself.

**Comment by VanathiTrek** [comment]
Its Fine,Thank You for your reply. If any help needed will contact you.

On Tue, Mar 24, 2015 at 5:23 AM, Vincent Taverna <notifications@github.com>
wrote:

> Closed #9 <https://github.com/getlua/boxviewrb/issues/9>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlua/boxviewrb/issues/9#event-262947139>.
>



-- 
-Regards
   *V.Vanathi*
*   Technology Associate*
*   Trekbin Technologies Pvt. Ltd.*
*   E-mail id : vanathi.vijayakumar@trekbin.com
<vanathi.vijayakumar@trekbin.com>*
*   Skype Name : vanathi.vijayakumar1*
